proyecto_python_coder-main/simple_blog/posts/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [

    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='blog'
    ),

    path(
        route='posts/<slug:url>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),

    path(
        route='posts/save_comment',
        view=views.save_comment,
        name='save_comment'
    ),

]

proyecto_python_coder-main/simple_blog/simple_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path(
        route='sobre-mi',
        view=TemplateView.as_view(template_name='about.html'),
        name='about'
    ),
    path('', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto_python_coder-main/simple_blog/users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from users import views

urlpatterns = [
    path(
        route='login',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='registro',
        view=views.SignupView.as_view(),
        name='register'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='registro_completado/',
        view=TemplateView.as_view(template_name='users/registerok.html'),
        name='registerok'
    ),
]

proyecto_python_coder-main/simple_blog/templates/about.html
{% extends "base.html" %}
{% block title %}Simple blog - Sobre mi{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <h1 class="mt-4">Sobre mi</h1>
      <hr>
      <img class="img-fluid rounded" src="http://placehold.it/150x200" alt="">
      <hr>
      <p class="lead">Nuestra Historia</p>
        
        <p>Cuando fundamos Be Digital Trend, también nos preguntamos qué era una agencia de marketing
        digital. Y qué éramos nosotros. En un rubro como el nuestro, de cambios y transformaciones vertiginosas, estas
        preguntas se renuevan constantemente y aún nos inquietan y asombran. Hasta cierto punto, todavía hoy las estamos
        respondiendo junto a nuestros clientes. Con el tiempo y la experiencia llegamos a algunas conclusiones. Hoy
        creemos que una agencia de marketing digital desarrolla estrategias digitales integrales de acuerdo al tamaño de
        cada empresa. Siempre busca ampliar los horizontes comerciales y mejorar la comunicación. En gran medida, una
        agencia digital se ocupa de desarrollar una estrategia digital para transmitir el mensaje de una marca al
        público adecuado.</p>

        <p>Nuestro equipo Junto a un equipo multidisciplinario de jóvenes profesionales , creativos, innovadores y
        orientados a resultados, generamos casos de éxito a nuestros clientes. Nuestro grupo se compone de expertos en
        diferentes áreas tales como diseñadores gráficos, diseñadores web, publicistas, redactores seo, community
        managers, project managers, editores audiovisuales.</p>

        <p>Nuestro CEO Ivana Aranaz es experta en Marketing Digital. Es directora de marketing de
        varias empresas de latinoamerica, en las cuales implementó diferentes estrategias adaptadas a la diversidades de
        los escenarios económicos de los diferentes paises.</p>
      <hr>
    </div>
    {% endblock %}

proyecto_python_coder-main/simple_blog/templates/base.html
<!DOCTYPE html>
<html lang="es">
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <title>{% block title %}Simple blog{% endblock %}</title>
      {% load bootstrap4 %}
      {% bootstrap_css %}
      {% load static %}
      <link rel="stylesheet" href="{% static 'css/blog-home.css' %}">
   </head>
   <body>
      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
         <div class="container">
            <a class="navbar-brand" href="{% url 'posts:blog' %}">Simple Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
               <ul class="navbar-nav ml-auto">
                  <li class="nav-item active">
                     <a class="nav-link" href="{% url 'posts:blog' %}">Blog
                     <span class="sr-only">(current)</span>
                     </a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'about' %}">Sobre mi</a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{request.user.username}}</a>
                     <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                     </div>
                  </li>
                  {% else %}
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link" href="{% url 'users:register' %}">Registro</a>
                  </li>
                  {% endif %}
               </ul>
            </div>
         </div>
      </nav>
      <!-- Page Content -->
      <div class="container">
         {% block content %}{% endblock %}    
         <!-- Sidebar Widgets Column -->
         <div class="col-md-4">
            <!-- Categories Widget -->
            <div class="card my-4">
               <h5 class="card-header">Categories</h5>
               <div class="card-body">
                  <div class="row">
                     <div class="col-lg-12">
                        <ul class="list-unstyled mb-0">
                          {% for category in categories %}
                          <li>
                              <a href="#">{{category.name}}</a>
                          </li>
                          {% endfor %}
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
            <!-- Side Widget -->
            <div class="card my-4">
               <h5 class="card-header">Novedades</h5>
               <div class="card-body">
                  Poner Novedades Aqui
               </div>
            </div>
         </div>
      </div>
      <!-- Footer -->
      <footer class="py-5 bg-dark">
         <div class="container">
            <p class="m-0 text-center text-white">Copyright Ivana Aranaz &copy; Simple Blog {% now "Y" %}</p>
         </div>
         <!-- /.container -->
      </footer>
      {% bootstrap_javascript jquery='full' %}
   </body>
</html>